Fix compilation error with freetype
This a for the following error with ROOT v6-20-08-alice1 and freetype:

```
-- Check for ROOT_LIBRARIES: Core;Imt;RIO;Net;Hist;Graf;Graf3d;Gpad;ROOTVecOps;Tree;TreePlayer;Rint;Postscript;Matrix;Physics;MathCore;Thread;MultiProc;ROOTDataFrame;freetype;Unfold
-- Check for ROOT_CORE_LIBRARY: /opt/alice/sw/osx_x86-64/ROOT/v6-20-08-alice1-local1/lib/libCore.so -- ok
...
-- Check for ROOT_ROOTDATAFRAME_LIBRARY: /opt/alice/sw/osx_x86-64/ROOT/v6-20-08-alice1-local1/lib/libROOTDataFrame.so -- ok
-- Check for ROOT_FREETYPE_LIBRARY: freetype -- failed
-- Check for ROOT_UNFOLD_LIBRARY: /opt/alice/sw/osx_x86-64/ROOT/v6-20-08-alice1-local1/lib/libUnfold.so -- ok
-- Check for libdl.so: /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/lib/libdl.tbd
-- ROOT was built with C++11 support
CMake Error at /usr/local/Cellar/cmake/3.20.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find ROOT (missing: ROOT_LIBRARIES ROOT_FREETYPE_LIBRARY)
  (Required is at least version "5.34")
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.20.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindROOT.cmake:289 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:26 (find_package)
```